### PR TITLE
feat: Add Pollerd statistics and JVM memory metrics

### PR DESCRIPTION
**Pull request by indigo423**
Created the visualization for current metrics for JVM memory and Pollerd scheduler and thread pools. Including time series graphs.

Firefox_Screenshot_2023-10-09T13-11-13 967Z

Firefox_Screenshot_2023-10-09T13-12-16 083Z

Resolve: #1
Resolve: #5

### CODE REVIEW

**Comment by indigo423** [comment]
@mmahacek I've fixed the active thread pool for Pollerd. I had to remove the variable for switching the data source. During import of the dashboard, the user has to pick one of his existing data sources and will replace the ${datasource} variable which is the reason a user can't switch the data source later. I don't have a way to fix this.

**Comment by mmahacek** [comment]
Double check the $node variable is also using the $dataSource variable.

**Comment by mmahacek** [comment]
I notice that on my 32.x instances, the JVM Swap graphs return `0` for all timestamps, but my 31.x instances return meaningful data. This causes those graphs to display an error due to divide by zero, but that's not a dashboard issue.

**Review by mmahacek — APPROVED** [review]
Pollerd stats look good.

**Pull request merged**
